# -*- coding: utf-8 -*-
"""language tanslation1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HhUMA5wNOGEeoSLFGRcHyyhE5SKcqQAb
"""

!pip install -q gradio
!pip install -q transformers

import gradio as gr

gr.__version__

import transformers

transformers.__version__

from transformers import pipeline

translation_pipeline = pipeline("translation_en_to_de")

result = translation_pipeline("I like mathematics and computers")

result

result[0]["translation_text"]



def translate_gradio(input):
  result = translation_pipeline(input)
  return result[0]["translation_text"]



translate_interface = gr.Interface(fn = translate_gradio,
                                   inputs = "text",
                                   outputs = "text")



translate_interface.launch(debug=True)